# Generated by Django 6.0 on 2026-01-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name_primary', models.CharField(max_length=200)),
                ('artist_name_secondary', models.CharField(blank=True, default='', max_length=200)),
                ('artist_type', models.CharField(choices=[('PERSON', 'Person'), ('BAND', 'Band')], default='BAND', max_length=10)),
                ('display_name', models.CharField(editable=False, max_length=220)),
                ('sort_name', models.CharField(db_index=True, editable=False, max_length=220)),
                ('alpha_bucket', models.CharField(db_index=True, editable=False, max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
