# Generated by Django 6.0 on 2026-01-08 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_binned', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_vinyl', models.BooleanField(default=False)),
                ('requires_speed', models.BooleanField(default=False)),
                ('default_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_types', to='catalog.storagezone')),
            ],
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pressing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_items', to='catalog.artist')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_items', to='catalog.mediatype')),
                ('zone_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='override_items', to='catalog.storagezone')),
            ],
        ),
    ]
