# Generated by Django 6.0 on 2026-01-08 15:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_storagezone_mediatype_mediaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicalBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity_override', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logical_bins', to='catalog.storagezone')),
            ],
            options={
                'ordering': ['zone__code', 'number'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('bin_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_bins', to='catalog.storagezone')),
            ],
            options={
                'ordering': ['zone__code', 'shelf_number', 'bin_number'],
            },
        ),
        migrations.CreateModel(
            name='BinMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('logical_bin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='catalog.logicalbin')),
                ('physical_bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='catalog.physicalbin')),
            ],
        ),
        migrations.AddConstraint(
            model_name='logicalbin',
            constraint=models.UniqueConstraint(fields=('zone', 'number'), name='uniq_logicalbin_zone_number'),
        ),
        migrations.AddConstraint(
            model_name='physicalbin',
            constraint=models.UniqueConstraint(fields=('zone', 'shelf_number', 'bin_number'), name='uniq_physicalbin_zone_shelf_bin'),
        ),
        migrations.AddConstraint(
            model_name='binmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('physical_bin',), name='uniq_active_mapping_per_physicalbin'),
        ),
    ]
