# Generated by Django 6.0 on 2026-01-08 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_logicalbin_physicalbin_binmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='logical_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_items', to='catalog.logicalbin'),
        ),
    ]
