# Generated by Django 6.0 on 2026-01-08 15:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_sortbucket_mediaitem_bucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketBinRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_bin', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('end_bin', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bin_ranges', to='catalog.sortbucket')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bucket_ranges', to='catalog.storagezone')),
            ],
            options={
                'ordering': ['zone__code', 'start_bin', 'end_bin'],
                'constraints': [models.UniqueConstraint(fields=('zone', 'bucket'), name='uniq_bucket_range_per_zone_bucket'), models.CheckConstraint(condition=models.Q(('end_bin__gte', models.F('start_bin'))), name='chk_bucket_range_end_gte_start')],
            },
        ),
    ]
