# Generated by Django 6.0 on 2026-01-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_bucketbinrange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='owner',
            field=models.CharField(choices=[('ME', 'Mine'), ('BIL', 'Brother-in-law')], default='ME', max_length=10),
        ),
    ]
