# Generated by Django 6.0 on 2026-01-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_artist_options_mediaitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagezone',
            name='sort_strategy',
            field=models.CharField(choices=[('BUCKETED', 'Bucketed (uses bucket bin ranges)'), ('ALPHA_ONLY', 'Alpha-only (ignores buckets)')], default='BUCKETED', max_length=16),
        ),
    ]
