# Generated by Django 6.0 on 2026-01-09 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_storagezone_sort_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagezone',
            name='default_bin_capacity',
            field=models.PositiveIntegerField(default=100, help_text='Default max items per logical bin in this zone (used unless a bin has capacity_override).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
