# Generated by Django 6.0 on 2026-01-10 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_storagezone_default_bin_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebinRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.sortbucket')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.storagezone')),
            ],
        ),
        migrations.CreateModel(
            name='RebinMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('old_physical_bin_label', models.CharField(blank=True, default='', max_length=128)),
                ('new_physical_bin_label', models.CharField(blank=True, default='', max_length=128)),
                ('is_done', models.BooleanField(default=False)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebin_moves', to='catalog.mediaitem')),
                ('new_logical_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.logicalbin')),
                ('old_logical_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.logicalbin')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='catalog.rebinrun')),
            ],
            options={
                'indexes': [models.Index(fields=['is_done'], name='catalog_reb_is_done_c3f353_idx'), models.Index(fields=['created_at'], name='catalog_reb_created_c438f3_idx')],
            },
        ),
    ]
