# Generated by Django 6.0 on 2026-01-12 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rebinrun_rebinmove'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='filed_under_artist',
            field=models.ForeignKey(blank=True, help_text='Optional artist to file this artist under for sorting/binning', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_here', to='catalog.artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='name_suffix',
            field=models.CharField(blank=True, default='', help_text='Suffix like Jr, Sr, II, III (PERSON artists only)', max_length=10),
        ),
    ]
