# Generated by Django 6.0 on 2026-01-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_artist_filed_under_artist_artist_name_suffix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['sort_name'], 'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'ordering': ['artist__sort_name', 'title']},
        ),
        migrations.AlterModelOptions(
            name='mediatype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='rebinmove',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rebinrun',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storagezone',
            options={'ordering': ['code']},
        ),
    ]
