# Generated by Django 6.0 on 2026-01-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_artist_options_alter_mediaitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='master_key',
            field=models.CharField(blank=True, db_index=True, help_text='Stable ID from the legacy catalog (e.g., A1234). Used for idempotent imports.', max_length=20, null=True, unique=True),
        ),
    ]
