# Generated by Django 6.0 on 2026-01-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_mediaitem_master_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='release_year',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
