# Generated by Django 6.0 on 2026-01-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_mediaitem_release_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'ordering': ['title']},
        ),
    ]
