# Generated by Django 6.0 on 2026-01-20 22:03
# Patched to avoid DuplicateTable/DuplicateColumn errors when DB already contains
# Tag/ArtistTag/MediaItemTag tables and StorageZone.bins_per_shelf.

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0018_storagezone_bins_per_shelf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediaitem",
            options={"ordering": ["artist__sort_name", "title"]},
        ),

        # StorageZone.bins_per_shelf already exists in DB; keep state aligned without DB op.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="storagezone",
                    name="bins_per_shelf",
                    field=models.PositiveIntegerField(
                        default=8,
                        help_text=(
                            "How many physical bins exist per shelf in this zone "
                            "(used to compute linear bin numbers)."
                        ),
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
        ),

        migrations.AlterField(
            model_name="mediaitem",
            name="release_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),

        # Tag system already exists in DB; keep migration state aligned without DB ops.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Tag",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.CharField(max_length=120)),
                        ("slug", models.SlugField(blank=True, max_length=140)),
                        (
                            "scope",
                            models.CharField(
                                choices=[("ARTIST", "Artist"), ("MEDIA_ITEM", "Media Item")],
                                max_length=20,
                            ),
                        ),
                        ("sort_order", models.PositiveIntegerField(default=0)),
                        ("tag_note", models.TextField(blank=True)),
                    ],
                    options={
                        "ordering": ("scope", "sort_order", "name"),
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("scope", "slug"),
                                name="uniq_tag_scope_slug",
                            ),
                            models.UniqueConstraint(
                                fields=("scope", "name"),
                                name="uniq_tag_scope_name",
                            ),
                        ],
                    },
                ),
            ],
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="MediaItemTag",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "media_item",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="media_item_tags",
                                to="catalog.mediaitem",
                            ),
                        ),
                        (
                            "tag",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="media_item_tags",
                                to="catalog.tag",
                            ),
                        ),
                    ],
                ),
            ],
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="ArtistTag",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "artist",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="artist_tags",
                                to="catalog.artist",
                            ),
                        ),
                        (
                            "tag",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="artist_tags",
                                to="catalog.tag",
                            ),
                        ),
                    ],
                ),
            ],
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="artist",
                    name="tags",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="artists",
                        through="catalog.ArtistTag",
                        to="catalog.tag",
                    ),
                ),
            ],
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="mediaitem",
                    name="tags",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="media_items",
                        through="catalog.MediaItemTag",
                        to="catalog.tag",
                    ),
                ),
            ],
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddConstraint(
                    model_name="mediaitemtag",
                    constraint=models.UniqueConstraint(
                        fields=("media_item", "tag"),
                        name="uniq_media_item_tag",
                    ),
                ),
            ],
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddConstraint(
                    model_name="artisttag",
                    constraint=models.UniqueConstraint(
                        fields=("artist", "tag"),
                        name="uniq_artist_tag",
                    ),
                ),
            ],
        ),
    ]
