# Generated manually to repair "state-only" (fake) migrations in 0016-0019.
from django.db import migrations

TAG_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS catalog_tag (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR(200) NOT NULL,
  slug         VARCHAR(220) NOT NULL,
  scope        VARCHAR(20)  NOT NULL DEFAULT 'MEDIA_ITEM',
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT catalog_tag_scope_slug_uniq UNIQUE (scope, slug)
);
"""

MEDIAITEMTAG_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS catalog_mediaitemtag (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  media_item_id BIGINT NOT NULL REFERENCES catalog_mediaitem(id) ON DELETE CASCADE,
  tag_id        BIGINT NOT NULL REFERENCES catalog_tag(id) ON DELETE CASCADE
);
"""

ARTISTTAG_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS catalog_artisttag (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  artist_id   BIGINT NOT NULL REFERENCES catalog_artist(id) ON DELETE CASCADE,
  tag_id      BIGINT NOT NULL REFERENCES catalog_tag(id) ON DELETE CASCADE
);
"""

class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0019_alter_mediaitem_options_storagezone_bins_per_shelf_and_more"),
    ]

    operations = [
        migrations.RunSQL(TAG_TABLE_SQL, reverse_sql="DROP TABLE IF EXISTS catalog_tag CASCADE;"),
        migrations.RunSQL(MEDIAITEMTAG_TABLE_SQL, reverse_sql="DROP TABLE IF EXISTS catalog_mediaitemtag CASCADE;"),
        migrations.RunSQL(ARTISTTAG_TABLE_SQL, reverse_sql="DROP TABLE IF EXISTS catalog_artisttag CASCADE;"),
    ]
