# Generated by Django 6.0 on 2026-01-29 17:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_add_tag_note_column_db'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('artist_name_primary'), django.db.models.functions.text.Lower('artist_name_secondary'), django.db.models.functions.text.Lower('name_suffix'), models.F('artist_type'), name='uniq_artist_identity_ci'),
        ),
    ]
